<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>wavemap_all_ros2</name>
  <version>2.2.1</version>
  <description>Metapackage that builds all wavemap ROS 2 packages.</description>

  <maintainer email="akhilmjohn@gmail.com">Akhil John</maintainer>
  <license>BSD</license>
  <url>https://github.com/ethz-asl/wavemap</url>

  <author email="akhilmjohn@gmail.com">Akhil John</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>wavemap_ros2</exec_depend>
  <exec_depend>wavemap_msgs_ros2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
